-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.exercises
(
    exercise_id serial NOT NULL,
    exercise_name character varying(200) NOT NULL,
    muscle_group character varying(100),
    PRIMARY KEY (exercise_id)
);

CREATE TABLE IF NOT EXISTS public.training_plans
(
    plan_id serial NOT NULL,
    plan_name character varying(50) NOT NULL,
    start_date date NOT NULL,
    end_date date,
    PRIMARY KEY (plan_id)
);

CREATE TABLE IF NOT EXISTS public.plan_exercises
(
    plan_exercise_id serial NOT NULL,
    plan_id integer NOT NULL,
    exercise_id integer NOT NULL,
    day_of_week character varying(20) NOT NULL,
    sets integer NOT NULL,
    reps integer NOT NULL,
    planned_weight numeric(5, 2),
    PRIMARY KEY (plan_exercise_id)
);

CREATE TABLE IF NOT EXISTS public.workout_sessions
(
    session_id serial NOT NULL,
    plan_id integer NOT NULL,
    session_date date NOT NULL,
    day_of_week character varying(20) NOT NULL,
    PRIMARY KEY (session_id)
);

CREATE TABLE IF NOT EXISTS public.session_exercises
(
    session_exercise_id serial NOT NULL,
    session_id integer NOT NULL,
    exercise_id integer NOT NULL,
    set_number integer NOT NULL,
    reps_completed integer NOT NULL,
    weight_used numeric(5, 2) NOT NULL,
    notes text,
    PRIMARY KEY (session_exercise_id)
);

ALTER TABLE IF EXISTS public.plan_exercises
    ADD FOREIGN KEY (plan_id)
    REFERENCES public.training_plans (plan_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.plan_exercises
    ADD FOREIGN KEY (exercise_id)
    REFERENCES public.exercises (exercise_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.workout_sessions
    ADD FOREIGN KEY (plan_id)
    REFERENCES public.training_plans (plan_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.session_exercises
    ADD FOREIGN KEY (session_id)
    REFERENCES public.workout_sessions (session_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.session_exercises
    ADD FOREIGN KEY (exercise_id)
    REFERENCES public.exercises (exercise_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;