-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.exercises
(
    exercise_id serial NOT NULL,
    exercise_name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    muscle_group character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT exercises_pkey PRIMARY KEY (exercise_id)
);

COMMENT ON TABLE public.exercises
    IS 'List of exercises

Each month check and add new exercises if they don''t exist';

CREATE TABLE IF NOT EXISTS public.plan_exercises
(
    plan_exercise_id serial NOT NULL,
    plan_id integer NOT NULL,
    exercise_id integer NOT NULL,
    day_of_week character varying(20) COLLATE pg_catalog."default" NOT NULL,
    warmup_sets integer,
    working_sets integer NOT NULL,
    reps text COLLATE pg_catalog."default" NOT NULL,
    planned_weight numeric(5, 2),
    rest_between_sets_min integer,
    rest_between_sets_max integer,
    rest_after_exercise_min integer,
    rest_after_exercise_max integer,
    CONSTRAINT plan_exercises_pkey PRIMARY KEY (plan_exercise_id)
);

COMMENT ON TABLE public.plan_exercises
    IS 'Describes what exactly is in monthly training plan. What exercises, how many sets, reps, what is the rest time between sets and exercises';

CREATE TABLE IF NOT EXISTS public.session_exercises
(
    session_exercise_id serial NOT NULL,
    session_id integer NOT NULL,
    exercise_id integer NOT NULL,
    set_number integer NOT NULL,
    reps_completed integer NOT NULL,
    weight_used numeric(5, 2),
    notes text COLLATE pg_catalog."default",
    CONSTRAINT session_exercises_pkey PRIMARY KEY (session_exercise_id)
);

COMMENT ON TABLE public.session_exercises
    IS 'Details for each exercise done during workout, recording sets/reps done, weight used and notes';

CREATE TABLE IF NOT EXISTS public.training_plans
(
    plan_id serial NOT NULL,
    plan_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    start_date date NOT NULL,
    end_date date,
    CONSTRAINT training_plans_pkey PRIMARY KEY (plan_id)
);

COMMENT ON TABLE public.training_plans
    IS 'Monthly training plans
New plan is being added once per month when new plan is provided by coach.

Ex:
Plan Styczeń | 2025-01-01 | 2025-01-31';

CREATE TABLE IF NOT EXISTS public.workout_sessions
(
    session_id serial NOT NULL,
    plan_id integer NOT NULL,
    session_date date NOT NULL,
    day_of_week character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT workout_sessions_pkey PRIMARY KEY (session_id)
);

COMMENT ON TABLE public.workout_sessions
    IS 'Records each training session done per training plan';

ALTER TABLE IF EXISTS public.plan_exercises
    ADD CONSTRAINT plan_exercises_exercise_id_fkey FOREIGN KEY (exercise_id)
    REFERENCES public.exercises (exercise_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.plan_exercises
    ADD CONSTRAINT plan_exercises_plan_id_fkey FOREIGN KEY (plan_id)
    REFERENCES public.training_plans (plan_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.session_exercises
    ADD CONSTRAINT session_exercises_exercise_id_fkey FOREIGN KEY (exercise_id)
    REFERENCES public.exercises (exercise_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.session_exercises
    ADD CONSTRAINT session_exercises_session_id_fkey FOREIGN KEY (session_id)
    REFERENCES public.workout_sessions (session_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.workout_sessions
    ADD CONSTRAINT workout_sessions_plan_id_fkey FOREIGN KEY (plan_id)
    REFERENCES public.training_plans (plan_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;